spring.application.name=AgriAutomation

spring.datasource.hikari.connectionTimeout=20000
spring.datasource.hikari.maximumPoolSize=5

# PostgreSQL Database connection details
spring.datasource.url=${POSTGRES_URL}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA and Hibernate configurations
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.web.resources.add-mappings=false
server.error.include-stacktrace=never

app.jwtSecret=${JWT_SECRET}
app.jwtAccessExpirationMs=${JWT_ACCESS_EXPIRATION}
app.jwtRefreshExpirationMs=${JWT_REFRESH_EXPIRATION}
app.allowedOrigin=${ALLOWED_ORIGIN}
